"use strict";

const THEMES = {
  notion: {
    id: "notion",
    name: "Notion",
    styles: {
      container:
        'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.6 !important; color: #37352f !important; background-color: #ffffff !important; word-wrap: break-word;',
      h1: "font-size: 34px; font-weight: 700; color: #37352f !important; line-height: 1.2 !important; margin: 38px 0 8px; letter-spacing: -0.02em;",
      h2: "font-size: 26px; font-weight: 600; color: #37352f !important; line-height: 1.3 !important; margin: 32px 0 8px;",
      h3: "font-size: 21px; font-weight: 600; color: #37352f !important; line-height: 1.35 !important; margin: 28px 0 8px;",
      h4: "font-size: 18px; font-weight: 600; color: #37352f !important; line-height: 1.4 !important; margin: 24px 0 8px;",
      p: "margin: 4px 0 !important; line-height: 1.6 !important; color: #37352f !important;",
      strong: "font-weight: 700; color: #37352f !important;",
      em: "font-style: italic; color: #37352f !important;",
      a: "color: #37352f !important; text-decoration: underline; text-underline-offset: 3px; text-decoration-color: rgba(55,53,47,0.4);",
      ul: "margin: 4px 0; padding-left: 26px;",
      ol: "margin: 4px 0; padding-left: 26px;",
      li: "margin: 2px 0; line-height: 1.6 !important; color: #37352f !important;",
      blockquote: "margin: 8px 0; padding: 4px 16px; background-color: transparent !important; border-left: 3px solid #37352f; color: #37352f !important; border-radius: 0;",
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 2px 5px; background-color: #f7f6f3 !important; color: #eb5757 !important; border-radius: 3px; font-size: 13px !important; line-height: 1.5 !important;',
      pre: "margin: 16px 0; padding: 20px; background-color: #f7f6f3 !important; border-radius: 4px; overflow-x: auto; font-size: 13px !important; line-height: 1.5 !important;",
      hr: "margin: 24px auto; border: none; height: 1px; background-color: #e9e9e7 !important; width: 100%;",
      img: "max-width: 100%; height: auto; display: block; margin: 16px auto; border-radius: 2px;",
      table: "width: 100%; margin: 16px 0; border-collapse: collapse; font-size: 15px;",
      th: "background-color: #f7f6f3 !important; padding: 8px 12px; text-align: left; font-weight: 600; color: #37352f !important; border: 1px solid #e9e9e7;",
      td: "padding: 8px 12px; border: 1px solid #e9e9e7; color: #37352f !important;",
      tr: "border: none;",
    },
  },
  github: {
    id: "github",
    name: "GitHub",
    styles: {
      container:
        'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; font-size: 16px; line-height: 1.6 !important; color: #1f2328 !important; background-color: #ffffff !important; word-wrap: break-word;',
      h1: "font-size: 32px; font-weight: 600; color: #1f2328 !important; line-height: 1.25 !important; margin: 24px 0 16px; padding-bottom: 10px; border-bottom: 1px solid #d1d9e0;",
      h2: "font-size: 24px; font-weight: 600; color: #1f2328 !important; line-height: 1.25 !important; margin: 24px 0 16px; padding-bottom: 8px; border-bottom: 1px solid #d1d9e0;",
      h3: "font-size: 20px; font-weight: 600; color: #1f2328 !important; line-height: 1.25 !important; margin: 24px 0 16px;",
      h4: "font-size: 16px; font-weight: 600; color: #1f2328 !important; line-height: 1.25 !important; margin: 24px 0 16px;",
      p: "margin: 16px 0 !important; line-height: 1.6 !important; color: #1f2328 !important;",
      strong: "font-weight: 600; color: #1f2328 !important;",
      em: "font-style: italic; color: #1f2328 !important;",
      a: "color: #0969da !important; text-decoration: underline; text-underline-offset: 2px;",
      ul: "margin: 16px 0; padding-left: 28px;",
      ol: "margin: 16px 0; padding-left: 28px;",
      li: "margin: 4px 0; line-height: 1.6 !important; color: #1f2328 !important;",
      blockquote: "margin: 16px 0; padding: 8px 16px; background-color: transparent !important; border-left: 4px solid #d0d7de; color: #656d76 !important; border-radius: 0;",
      code: 'font-family: "SF Mono", Consolas, "Liberation Mono", Menlo, monospace; padding: 3px 6px; background-color: rgba(175,184,193,0.2) !important; color: #1f2328 !important; border-radius: 6px; font-size: 13px !important; line-height: 1.5 !important;',
      pre: "margin: 16px 0; padding: 16px; background-color: #f6f8fa !important; border-radius: 6px; overflow-x: auto; font-size: 13px !important; line-height: 1.45 !important;",
      hr: "margin: 24px auto; border: none; height: 3px; background-color: #d1d9e0 !important; width: 100%; border-radius: 2px;",
      img: "max-width: 100%; height: auto; display: block; margin: 16px auto; border-radius: 6px;",
      table: "width: 100%; margin: 16px 0; border-collapse: collapse; font-size: 15px;",
      th: "background-color: #f6f8fa !important; padding: 8px 16px; text-align: left; font-weight: 600; color: #1f2328 !important; border: 1px solid #d1d9e0;",
      td: "padding: 8px 16px; border: 1px solid #d1d9e0; color: #1f2328 !important;",
      tr: "border: none;",
    },
  },
  sspai: {
    id: "sspai",
    name: "少数派",
    styles: {
      container:
        'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.8 !important; color: #333333 !important; background-color: #ffffff !important; word-wrap: break-word;',
      h1: "font-size: 28px; font-weight: 700; color: #d71a1b !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.01em;",
      h2: "font-size: 22px; font-weight: 700; color: #333333 !important; line-height: 1.35 !important; margin: 32px 0 14px; padding-left: 12px; border-left: 4px solid #d71a1b;",
      h3: "font-size: 22px; font-weight: 700; color: #333333 !important; line-height: 1.35 !important; margin: 36px 0 18px; padding: 10px 14px; background-color: #fef7f7 !important; border-left: 4px solid #d71a1b; border-radius: 0 12px 12px 0;",
      h4: "font-size: 16px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 24px 0 12px;",
      p: "margin: 20px 0 !important; line-height: 1.8 !important; color: #333333 !important; font-weight: 400 !important;",
      strong: "font-weight: 700; color: #d71a1b !important;",
      em: "font-style: italic; color: #666 !important;",
      a: "color: #d71a1b !important; text-decoration: none; border-bottom: 1px solid rgba(215,26,27,0.3); padding-bottom: 1px;",
      ul: "margin: 16px 0; padding-left: 28px;",
      ol: "margin: 16px 0; padding-left: 28px;",
      li: "margin: 8px 0; line-height: 1.8 !important; color: #333333 !important; font-weight: 400 !important;",
      blockquote: "margin: 24px 0; padding: 16px 20px; background-color: #fef7f7 !important; border-left: 4px solid #d71a1b; color: #555 !important; border-radius: 4px; font-weight: 400 !important;",
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #fff5f5 !important; color: #d71a1b !important; border-radius: 4px; font-size: 13px !important; line-height: 1.5 !important;',
      pre: "margin: 24px 0; padding: 20px; background-color: #fafafa !important; border-radius: 8px; overflow-x: auto; font-size: 13px !important; line-height: 1.5 !important; border: 1px solid #f0f0f0;",
      hr: "margin: 36px auto; border: none; height: 1px; background-color: #eee !important; width: 100%;",
      img: "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 8px;",
      table: "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;",
      th: "background-color: #fef7f7 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #333 !important; border: 1px solid #f0e0e0;",
      td: "padding: 12px 16px; border: 1px solid #f0e0e0; color: #333333 !important;",
      tr: "border: none;",
    },
  },
  mint: {
    id: "mint",
    name: "薄荷",
    styles: {
      container:
        'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #2d4a3e !important; background-color: #f0faf5 !important; word-wrap: break-word;',
      h1: "font-size: 32px; font-weight: 700; color: #1a7a5a !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;",
      h2: "font-size: 26px; font-weight: 600; color: #1a7a5a !important; line-height: 1.35 !important; margin: 32px 0 16px;",
      h3: "font-size: 21px; font-weight: 600; color: #2d4a3e !important; line-height: 1.4 !important; margin: 28px 0 14px;",
      h4: "font-size: 18px; font-weight: 600; color: #2d4a3e !important; line-height: 1.4 !important; margin: 24px 0 12px;",
      p: "margin: 18px 0 !important; line-height: 1.7 !important; color: #2d4a3e !important;",
      strong: "font-weight: 700; color: #1a7a5a !important;",
      em: "font-style: italic; color: #5a8a72 !important;",
      a: "color: #1a7a5a !important; text-decoration: none; border-bottom: 1px solid rgba(26,122,90,0.3); padding-bottom: 1px;",
      ul: "margin: 16px 0; padding-left: 28px;",
      ol: "margin: 16px 0; padding-left: 28px;",
      li: "margin: 8px 0; line-height: 1.7 !important; color: #2d4a3e !important;",
      blockquote: "margin: 24px 0; padding: 16px 20px; background-color: #e0f5ec !important; border-left: 4px solid #1a7a5a; color: #3d5a4e !important; border-radius: 4px;",
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #e0f5ec !important; color: #1a7a5a !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: "margin: 24px 0; padding: 20px; background-color: #e0f5ec !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;",
      hr: "margin: 36px auto; border: none; height: 1px; background-color: #c8e6d8 !important; width: 100%;",
      img: "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 8px;",
      table: "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;",
      th: "background-color: #e0f5ec !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #2d4a3e !important; border: 1px solid #c8e6d8;",
      td: "padding: 12px 16px; border: 1px solid #c8e6d8; color: #2d4a3e !important;",
      tr: "border: none;",
    },
  },
  sunset: {
    id: "sunset",
    name: "日落",
    styles: {
      container:
        'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: Georgia, "Times New Roman", Times, serif; font-size: 16px; line-height: 1.8 !important; color: #3d2c1e !important; background-color: #fdf6ee !important; word-wrap: break-word;',
      h1: "font-size: 32px; font-weight: 700; color: #c0582a !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;",
      h2: "font-size: 26px; font-weight: 600; color: #c0582a !important; line-height: 1.35 !important; margin: 32px 0 16px;",
      h3: "font-size: 21px; font-weight: 600; color: #3d2c1e !important; line-height: 1.4 !important; margin: 28px 0 14px;",
      h4: "font-size: 18px; font-weight: 600; color: #3d2c1e !important; line-height: 1.4 !important; margin: 24px 0 12px;",
      p: "margin: 20px 0 !important; line-height: 1.8 !important; color: #3d2c1e !important;",
      strong: "font-weight: 700; color: #c0582a !important;",
      em: "font-style: italic; color: #8a6d4b !important;",
      a: "color: #c0582a !important; text-decoration: none; border-bottom: 1px solid rgba(192,88,42,0.3); padding-bottom: 1px;",
      ul: "margin: 16px 0; padding-left: 28px;",
      ol: "margin: 16px 0; padding-left: 28px;",
      li: "margin: 8px 0; line-height: 1.8 !important; color: #3d2c1e !important;",
      blockquote: "margin: 24px 0; padding: 16px 20px; background-color: #f8ead6 !important; border-left: 4px solid #e8a65d; color: #5a4232 !important; border-radius: 4px; font-style: italic;",
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #f5e6d0 !important; color: #c0582a !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: "margin: 24px 0; padding: 20px; background-color: #f5e6d0 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;",
      hr: "margin: 36px auto; border: none; height: 1px; background-color: #e8d4b8 !important; width: 100%;",
      img: "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;",
      table: "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;",
      th: "background-color: #f5e6d0 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #3d2c1e !important; border: 1px solid #e8d4b8;",
      td: "padding: 12px 16px; border: 1px solid #e8d4b8; color: #3d2c1e !important;",
      tr: "border: none;",
    },
  },
  wechat: {
    id: "wechat",
    name: "微信公众号原生",
    styles: {
      container:
        'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #333333 !important; background-color: #ffffff !important; word-wrap: break-word;',
      h1: "font-size: 32px; font-weight: 700; color: #111 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;",
      h2: "font-size: 26px; font-weight: 600; color: #111 !important; line-height: 1.35 !important; margin: 32px 0 16px;",
      h3: "font-size: 21px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 28px 0 14px;",
      h4: "font-size: 18px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 24px 0 12px;",
      p: "margin: 18px 0 !important; line-height: 1.7 !important; color: #333333 !important;",
      strong: "font-weight: 700; color: #07c160 !important; background-color: rgba(7,193,96,0.08); padding: 0 4px; border-radius: 4px;",
      em: "font-style: italic; color: #666 !important;",
      a: "color: #07c160 !important; text-decoration: none; border-bottom: 1px solid #07c160; padding-bottom: 1px;",
      ul: "margin: 16px 0; padding-left: 28px;",
      ol: "margin: 16px 0; padding-left: 28px;",
      li: "margin: 8px 0; line-height: 1.7 !important; color: #333333 !important;",
      blockquote: "margin: 24px 0; padding: 16px 20px; background-color: #f0f7f2 !important; border-left: 4px solid #07c160; color: #555 !important; border-radius: 4px;",
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #f0f7f2 !important; color: #07c160 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: "margin: 24px 0; padding: 20px; background-color: #f0f7f2 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;",
      hr: "margin: 36px auto; border: none; height: 1px; background-color: #eaeaea !important; width: 100%;",
      img: "max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;",
      table: "width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;",
      th: "background-color: #f0f7f2 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #333333 !important; border: 1px solid #d8e8dc;",
      td: "padding: 12px 16px; border: 1px solid #d8e8dc; color: #333333 !important;",
      tr: "border: none;",
    },
  },
};

function getTheme(themeId) {
  return THEMES[String(themeId || "").trim()] || THEMES.sspai;
}

module.exports = {
  THEMES,
  getTheme,
};
